### ISSUE TITLE
Android App crash updating Marks position

### ISSUE THREAD

**Issue by Userpack4** [glob3mobile/g3m#156]
Hi all,
I've implemented glob3 in my android app.
I've created a BluMarbleLayer and a Mark in onCreate method.
Then, in a Timer I have a routine "update" that is run every 1 seconds.
In the update routine I change the Mark position via setPosition with a new Geodetic3D position (lat, lon alt)
After some seconds I have this error and the App crash:

``````
java.lang.NullPointerException
            at org.glob3.mobile.generated.Mark.createGLState(Mark.java:122)
            at org.glob3.mobile.generated.Mark.render(Mark.java:854)
            at org.glob3.mobile.generated.MarksRenderer.render(MarksRenderer.java:194)
            at org.glob3.mobile.generated.CompositeRenderer.render(CompositeRenderer.java:147)
            at org.glob3.mobile.generated.G3MWidget.render(G3MWidget.java:212)
            at org.glob3.mobile.specific.ES2Renderer.onDrawFrame(ES2Renderer.java:63)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)```
Anyone can help me to find a solution ?
Thanks in advance.
``````

**Comment by DiegoGomezDeck** [comment]
Hi @silvioItaly 

It looks like you're calling G3M methods from am invalid thread, please take a look to #17

**Comment by Userpack4** [comment]
Thanks for the quick reply, PeriodicalTask solve my problem.
That's actually perfect! Thank you, again.
