### ISSUE TITLE
enabling / disabling elevation data causes crash

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#32]
I'm trying to dynamically enable / disable the display of elevation data by calling:

```
    g3mWidget.getG3MWidget().getPlanetRenderer().setElevationDataProvider(
                                        elevationMap ? dem : null, false);
```

where dem is a CompositeElevationDataProvider holding SingleBillElevationDataProvider objects, and elevationMap is a boolean value holding the preference if the elevation data should be shown. this seems to work for enabling elevation data (setting dem), and then disabling (setting null). but setting / resetting eventually results in the following exception:

```
12-20 10:31:33.495: E/AndroidRuntime(26498): FATAL EXCEPTION: GLThread 118043
12-20 10:31:33.495: E/AndroidRuntime(26498): java.lang.ClassCastException: org.glob3.mobile.generated.IndexedGeometryMesh cannot be cast to org.glob3.mobile.generated.MeshHolder
12-20 10:31:33.495: E/AndroidRuntime(26498):    at org.glob3.mobile.generated.Tile.getTessellatorMesh(Tile.java:171)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at org.glob3.mobile.generated.Tile.rawRender(Tile.java:325)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at org.glob3.mobile.generated.Tile.render(Tile.java:743)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at org.glob3.mobile.generated.PlanetRenderer.render(PlanetRenderer.java:484)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at org.glob3.mobile.generated.CompositeRenderer.render(CompositeRenderer.java:128)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at org.glob3.mobile.generated.G3MWidget.render(G3MWidget.java:234)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at org.glob3.mobile.specific.ES2Renderer.onDrawFrame(ES2Renderer.java:64)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
12-20 10:31:33.495: E/AndroidRuntime(26498):    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by mdelacalle** [comment]
Try to fix ASAP

**Comment by akosmaroy** [comment]
tnx. maybe I also have to queue this as a GTask?

**Comment by mdelacalle** [comment]
Please, could you try if is this problem? (The GTask problem)

**Comment by akosmaroy** [comment]
sure, but which queue should I put this change into? into the renderer thread: threadUtils.invokeInRendererThread()?

**Comment by DiegoGomezDeck** [comment]
Yes, all the changes to g3m has to be done from the renderer's thread

**Comment by akosmaroy** [comment]
putting these changes into a scheduled GTask seems to solve the issue
