### ISSUE TITLE
texImage2D should check for recycled Bitmaps on Android

### ISSUE THREAD

**Issue by mannodermaus** [glob3mobile/g3m#59]
Hey guys!

Occasionally, our app crashes when g3m tries to apply _GLUtils.texImage2D()_ on a bitmap that has already been recycled by Android. When trying to narrow the issue down, I noticed that, while _NativeGL2_Android.java_ does check for null input, it doesn't catch recycled bitmaps. I would like you to consider adding another edge case to the check in that particular method:

```
// NativeGL2_Android.java:
@Override
public void texImage2D(final IImage image, final int format) {
     checkOpenGLThread();
     final Bitmap bitmap = ((Image_Android) image).getBitmap();
     if (bitmap == null) {
          ILogger.instance().logError("texImage2D(): bitmap is null");
     } else if (bitmap.isRecycled()) {
          ILogger.instance().logError("texImage2D(): bitmap is recycled");
     } else {
          GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, bitmap, 0);
     }
}
```

**Comment by mdelacalle** [comment]
Hi Marcel,
We thinks that if we have a null there, probably we have a problem in another place.

Could you send us the code that give that crash?  (the code, a call stack, the error ....)

We mark the issue as a bug until we have more information and we can investigate what is happening and fix it in the core or wherever.

Thanks!!

**Comment by mannodermaus** [comment]
Here is the call stack leading up to the error:

```
java.lang.IllegalArgumentException: bitmap is recycled
at android.opengl.GLUtils.texImage2D(GLUtils.java:160)
at org.glob3.mobile.specific.NativeGL2_Android.texImage2D(SourceFile:352)
at org.glob3.mobile.generated.GL.uploadTexture(SourceFile:224)
at org.glob3.mobile.generated.TexturesHandler.getTextureIDReference(SourceFile:74)
at org.glob3.mobile.generated.Mark.render(SourceFile:596)
at org.glob3.mobile.generated.MarksRenderer.render(SourceFile:164)
at org.glob3.mobile.generated.CompositeRenderer.render(SourceFile:128)
at org.glob3.mobile.generated.G3MWidget.render(SourceFile:232)
at org.glob3.mobile.specific.ES2Renderer.onDrawFrame(SourceFile:64)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by DiegoGomezDeck** [comment]
Hello Marcel,

Does it happen after destroying and recreating the widget? Or it happens in any time?

**Comment by mannodermaus** [comment]
I'm not sure, as I did not produce the bug myself and haven't found a way to reproduce it yet.

**Comment by arjun-satish90** [comment]
If you run anything developed using cocos2d on samsung galaxy s4 and some others ,you would experience this particular error . The fix that I found across many sites is to use latest version of cocos2d .
