### ISSUE TITLE
polygon extruder fails when creatinging meshes

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#75]
the Polygon Extruder code fails when creating meshes, with the following stack trace:

```
java.lang.ArrayIndexOutOfBoundsException: -32768
    at java.util.ArrayList.elementData(ArrayList.java:400)
    at java.util.ArrayList.get(ArrayList.java:413)
    at com.glob3mobile.tools.mesh.G3Mesh.initializeNormals(G3Mesh.java:183)
    at com.glob3mobile.tools.mesh.G3Mesh.<init>(G3Mesh.java:159)
    at com.glob3mobile.tools.extruder.PolygonExtruder.writeG3MMeshJSON(PolygonExtruder.java:551)
    at com.glob3mobile.tools.extruder.PolygonExtruder.createG3MMeshJSON(PolygonExtruder.java:542)
    at com.glob3mobile.tools.extruder.PolygonExtruder.process(PolygonExtruder.java:353)
```

the polygon in question is rather large, and concave as well, will send you the point list in a private e-mail instead of pasting here

judging from the negative index, which looks like an overflow of the short type. but, AFAIK ArrayList and arrays in general are indexed by int, rather than short?

**Comment by DiegoGomezDeck** [comment]
Hi @akosmaroy 

It's short caused by OpenGL ES 2.0 specifications:  The indexes have to be shorts and not ints.

What's is happening is because the generated mesh is too large to render as one mesh.  If you really need  such big meshes, we need to change the logic in PolygonExtruder to split the big-mesh into smaller pieces.
