### ISSUE TITLE
The Vector-Tiles code fails on android device

### ISSUE THREAD

**Issue by DracoChow** [glob3mobile/g3m#85]
Hi,
I'v downloaded the newest G3M ,and started it successfully on my Eclipse.
All functions are well running ,except for the vector-tiles.I reset the urlTemplate like this:

```
final String urlTemplate = "http://igosoftware.dynds.org:8000/vectorial/scotland_buildings/GEOJSON/{level}/{x}/{y}.geojson";
……
new LevelTileCondition(10,17),
```

the system collapses when the VectorTilesAcitivity starts and the camer moves to ScotLand,with the following stack trace:

```
FATAL EXCEPTION: GLThread 3296
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
    at java.util.ArrayList.get(ArrayList.java:306)
    at org.glob3.mobile.generated.TiledVectorLayer.getRequestGEOJSONBufferData(TiledVectorLayer.java:218)
    at org.glob3.mobile.generated.TiledVectorLayerTileImageProvider$ImageAssembler.start(TiledVectorLayerTileImageProvider.java:360)
    at org.glob3.mobile.generated.TiledVectorLayerTileImageProvider.create(TiledVectorLayerTileImageProvider.java:564)
    at org.glob3.mobile.generated.CompositeTileImageProvider.create(CompositeTileImageProvider.java:493)
    at org.glob3.mobile.generated.DTT_TileTextureBuilder.start(DTT_TileTextureBuilder.java:92)at org.glob3.mobile.generated.DTT_TileTextureBuilderStartTask.execute

(DTT_TileTextureBuilderStartTask.java:20)
    at org.glob3.mobile.generated.FrameTasksExecutor.doPreRenderCycle(FrameTasksExecutor.java:185)
    at org.glob3.mobile.generated.G3MWidget.render(G3MWidget.java:193)
    at org.glob3.mobile.specific.ES2Renderer.onDrawFrame(ES2Renderer.java:63)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1651)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1363)
```

**Comment by DiegoGomezDeck** [comment]
Good catch, this error seems to occurs when the server doesn't response.

BTW, if you want to try with a working server:

``` C++
  const std::string urlTemplate = "http://glob3mobile.dyndns.org/vectorial/swiss-buildings-bson-new/{level}/{x}/{y}.bson";

  const Sector swissSector = Sector::fromDegrees(45.8176852, 5.956216,
                                                 47.803029, 10.492264);
  const int firstLevel = 2;
  const int maxLevel = 16;

  const GEORasterSymbolizer* symbolizer = new PinkishRasterSymbolizer();

  _tiledVectorLayer = TiledVectorLayer::newMercator(symbolizer,
                                                    urlTemplate,
                                                    swissSector,
                                                    firstLevel,
                                                    maxLevel,
                                                    TimeInterval::fromDays(30), // timeToCache
                                                    true,                       // readExpired
                                                    1,                          // transparency
                                                    new LevelTileCondition(10, 21),
                                                    new std::vector<const Info*>()
                                                    );
```
